baseURL: "https://leonardonatale.github.io/"
languageCode: "en-us"
title: "Leonardo Natale"
theme: "PaperMod"

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

pluralizeListTitles: false

markup:
  goldmark:
    renderer:
      unsafe: true
