main:
  - identifier: blog
    name: Blog
    url: /blog/
    weight: 10
  - identifier: bio
    name: Bio
    url: /bio/
    weight: 20
  # - identifier: example
  #   name: example.org
  #   url: https://example.org
  #   weight: 30
